credentials:
  usernames:
    renato_moretti:
      email: renato.moretti@xantage.co
      name: Renato Moretti
      password: $2b$12$w.aw8QdgaQLFO3ocYg.0deY7EoLTXJLP3.WkNsgIacrvCdsaxd9H6

    erik_quijano:
      email: erik.quijano@xantage.co
      name: Erik Quijano
      password: $2b$12$b69CEtkwe6oI1HwO9IOaReFxOnKMSmSHVP/1VdjK8l9LYkNwmTi4m

cookie:
  expiry_days: 30
  key: 5d41402abc4b2a76b9719d911017c592
  name: streamlit_auth_cookie

preauthorized:
  emails:
    - renato.moretti@xantage.co
    - erik.quijano@xantage.co
